/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
  });
  const Service = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };